# 奇语言配置文件

["关键字"]
"令" = "LET"
"设" = "SET"
"若" = "IF"
"再若" = "ELIF"
"否则" = "ELSE"
"当" = "WHILE"
"重复" = "REPEAT"
"返回" = "RETURN"
"读" = "INPUT"
"输出" = "OUTPUT"
"真" = "TRUE"
"假" = "FALSE"
"结构" = "STRUCT"
"对" = "IN"
"每项" = "EACH"
"包括" = "INCLUDE"
"调" = "INVOKE"

["类型名"]
"整数" = "TYPE_INT"
"小数" = "TYPE_FLOAT"
"文本" = "TYPE_STR"
"布尔" = "TYPE_BOOL"
"空" = "TYPE_VOID"
"无" = "TYPE_NULL"
"整数列" = "TYPE_LIST"
"小数列" = "TYPE_LIST"
"文本列" = "TYPE_LIST"

["中文运算符"]
"为" = "ASSIGN"
"等于" = "EQ"
"大于" = "GT"
"小于" = "LT"
"大于等于" = "GE"
"小于等于" = "LE"
"不等于" = "NE"
"加" = "ADD"
"减" = "SUB"
"乘" = "MUL"
"除" = "DIV"
"且" = "AND"
"或" = "OR"
"非" = "NOT"
"抑或" = "XOR"
"则" = "THEN"
"时" = "THEN"
"次" = "TIMES"
"含" = "CONTAINS"
"的" = "MEMBER_ACCESS"
"长度" = "LENGTH"

["ASCII运算符"]
"=" = "ASSIGN"
"==" = "EQ"
">" = "GT"
"<" = "LT"
">=" = "GE"
"<=" = "LE"
"!=" = "NE"
"+" = "ADD"
"-" = "SUB"
"*" = "MUL"
"/" = "DIV"
"&&" = "AND"
"||" = "OR"
"!" = "NOT"
"^" = "XOR"

["标点映射"]
"。" = "DOT"
"、" = "ENUM"
"：" = "COLON"
"；" = "SEMI"
"（" = "LPAREN"
"）" = "RPAREN"
"【" = "LBRACK"
"】" = "RBRACK"
"." = "DOT"
"," = "ENUM"
":" = "COLON"
";" = "SEMI"
"(" = "LPAREN"
")" = "RPAREN"
"[" = "LBRACK"
"]" = "RBRACK"

